// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task3;

namespace Task3.Migrations
{
    [DbContext(typeof(BISContext))]
    partial class BISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task3.Models.C_O", b =>
                {
                    b.Property<int>("O_ID");

                    b.Property<int>("P_ID");

                    b.HasKey("O_ID", "P_ID");

                    b.HasIndex("P_ID");

                    b.ToTable("C_O");
                });

            modelBuilder.Entity("Task3.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("O_ID");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("address");

                    b.HasKey("ID");

                    b.HasIndex("O_ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Task3.Models.Order", b =>
                {
                    b.Property<int>("O_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAddress");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Quantity");

                    b.HasKey("O_ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Task3.Models.Product", b =>
                {
                    b.Property<int>("P_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model");

                    b.Property<string>("P_Name")
                        .IsRequired();

                    b.Property<int>("Quantity");

                    b.HasKey("P_ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Task3.Models.C_O", b =>
                {
                    b.HasOne("Task3.Models.Order", "Order_O")
                        .WithMany("List_Product")
                        .HasForeignKey("O_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Task3.Models.Product", "Product_PRD")
                        .WithMany("listo")
                        .HasForeignKey("P_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Task3.Models.Customer", b =>
                {
                    b.HasOne("Task3.Models.Order", "Order_odr")
                        .WithMany("List_customer")
                        .HasForeignKey("O_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
